"""The DDL snapshot must not fall behind the ORM.

`sql/schema.sql` is generated by scripts/dump_schema_snapshot.sh and nothing at
runtime reads it, so nothing noticed when it went stale: it sat 24 tables and
the entire row-level-security layer behind head, which is worse than having no
snapshot at all — a reader saw 31 tables carrying no RLS policy and concluded
there was none.

A byte-exact check against the migrations is not available here. `alembic
upgrade head --sql` cannot run at all: four migrations (0018, 0019, 0021, 0026)
introspect and backfill from the live database, and alembic's offline mode
hands them a MockConnection with no exec_driver_sql. Migrating a real database
inside the suite is not available either — tests run on in-memory SQLite.

Matching the snapshot against `Base.metadata` needs neither, and catches the
drift that actually happened: a table or a column the application knows about
and the snapshot does not. It deliberately allows the snapshot to hold *more*
than the ORM, so a table with no ORM model does not fail the build.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from app.db.session import Base
import app.models  # noqa: F401  (registers every table on Base.metadata)


SNAPSHOT = Path(__file__).resolve().parents[1] / "sql" / "schema.sql"

# Tolerant of case and of an unqualified table name, so that a snapshot
# written in some other style reports the tables it genuinely lacks rather
# than failing to parse and blaming every table at once.
_CREATE_TABLE = re.compile(
    r"^CREATE\s+TABLE\s+(?:\w+\.)?(?P<name>\w+)\s*\((?P<body>.*?)^\);",
    re.DOTALL | re.MULTILINE | re.IGNORECASE,
)

# Table-constraint clauses share the block with columns and start with a
# keyword rather than a column name.
_NOT_A_COLUMN = frozenset(
    {"CONSTRAINT", "PRIMARY", "UNIQUE", "FOREIGN", "CHECK", "EXCLUDE"}
)


def _snapshot_tables() -> dict[str, set[str]]:
    """Column names per table, as the snapshot declares them."""
    text = SNAPSHOT.read_text(encoding="utf-8")
    tables: dict[str, set[str]] = {}
    for match in _CREATE_TABLE.finditer(text):
        columns = set()
        for line in match.group("body").splitlines():
            token = line.strip().split(" ", 1)[0].strip('",')
            if token and token.upper() not in _NOT_A_COLUMN:
                columns.add(token)
        tables[match.group("name")] = columns
    return tables


def test_snapshot_parses() -> None:
    assert SNAPSHOT.exists(), f"{SNAPSHOT} is missing"
    assert _snapshot_tables(), "no CREATE TABLE statements found — snapshot unreadable"


def test_snapshot_holds_every_orm_table() -> None:
    snapshot = _snapshot_tables()
    missing = sorted(set(Base.metadata.tables) - set(snapshot))
    assert not missing, (
        f"sql/schema.sql is missing {len(missing)} table(s): {', '.join(missing)}. "
        "Regenerate it with scripts/dump_schema_snapshot.sh."
    )


@pytest.mark.parametrize("table_name", sorted(Base.metadata.tables))
def test_snapshot_holds_every_orm_column(table_name: str) -> None:
    snapshot = _snapshot_tables()
    if table_name not in snapshot:
        pytest.skip("covered by test_snapshot_holds_every_orm_table")
    declared = {column.name for column in Base.metadata.tables[table_name].columns}
    missing = sorted(declared - snapshot[table_name])
    assert not missing, (
        f"sql/schema.sql has {table_name} without {', '.join(missing)}. "
        "Regenerate it with scripts/dump_schema_snapshot.sh."
    )
